# Material for MkDocs configuration
# https://squidfunk.github.io/mkdocs-material/getting-started/
#
# Mkdocs configuration
# https://www.mkdocs.org/getting-started/

site_name: PSModule Docs
site_url: https://psmodule.io/docs/
theme:
  name: material
  language: en
  custom_dir: ./overrides
  font:
    text: Mona Sans
    code: Source Code Pro
  logo: assets/images/icon.png
  favicon: assets/images/icon.png
  palette:
    # Palette toggle for automatic mode
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/link
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  icon:
    repo: material/github
    link: material/link-variant
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

nav:
  - Home: index.md
  - Projects:
      - PowerShell Modules:
          - PowerShell-Modules/index.md
          - Test-Specification: PowerShell-Modules/Test-Specification.md
          - Versioning: PowerShell-Modules/Versioning.md
      - GitHub Actions:
          - GitHub-Actions/index.md
          - Some More: GitHub-Actions/Some-More.md
          - Test Something: GitHub-Actions/Test-Something.md
          - Subtopic:
              - GitHub-Actions/Subtopic/index.md
              - Some More: GitHub-Actions/Subtopic/Some-More.md
              - Test Something: GitHub-Actions/Subtopic/Test-Something.md
  - Solutions:
      - Solutions/index.md
  - Blog:
      - Blog/index.md
  - About: About/index.md

repo_name: PSModule/docs
repo_url: https://github.com/PSModule/docs
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 - 2025 PSModule

plugins:
  - meta
  - search
  - social:
      cards_layout_options:
        font_family: Mona Sans
        background_color: deeppink
  - table-reader # https://timvink.github.io/mkdocs-table-reader-plugin/
  - blog:
      blog_dir: Blog
      post_dir: '{blog}/Posts'
      blog_toc: true
  - git-committers: # https://github.com/ojacques/mkdocs-git-committers-plugin-2
      repository: PSModule/docs
      branch: main
      exclude_committers:
        - 'web-flow'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - rss: # https://guts.github.io/mkdocs-rss-plugin/
      match_path: Blog/Posts/.*
      date_from_meta:
        as_creation: date.created
        as_update: date.updated

markdown_extensions:
  - toc:
      permalink: 'material/link-variant' # Adds a link icon to headings
  - attr_list
  - abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/links.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jedJWCPAhD
      name: PSModule on Discord
    - icon: material/powershell
      link: https://www.powershellgallery.com/profiles/PSModule.io
      name: PSModule on the PowerShell Gallery
    - icon: fontawesome/brands/github
      link: https://github.com/PSModule/
      name: PSModule on GitHub
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort.js
watch:
  - includes
