authors:
  MariusStorhaug:
    name: Marius Storhaug
    description: Developer and maintainer of PSModule
    avatar: https://avatars.githubusercontent.com/u/17722253?v=4
    slug: MariusStorhaug
    url: https://github.com/MariusStorhaug
