name: Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**
      - mkdocs.yml
      - .github/workflows/Docs.yml

env:
  GH_TOKEN: ${{ github.token }}
  MKDOCS_GIT_COMMITTERS_APIKEY: ${{ github.token }}

defaults:
  run:
    shell: pwsh

permissions:
  contents: write  # to push GitHub Pages to the gh-pages branch
  pages: write    # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Connect to GitHub
        uses: PSModule/GitHub-Script@v1

      - name: Install mkdocs-material
        env:
          GH_TOKEN: ${{ secrets.MATERIAL_FOR_MKDOCS_INSIDER_PAT }}
        run: |
          pip install git+https://$env:GH_TOKEN@github.com/squidfunk/mkdocs-material-insiders.git

      - name: Install plugins
        run: |
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-rss-plugin
          pip install "mkdocs-material[imaging]"
          pip install mkdocs-table-reader-plugin

      - name: Build mkdocs-material project
        run: |
          mkdocs build --config-file ./mkdocs.yml --strict --site-dir _site/

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
